# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ricardo Pedrotti
title: Data Engineer
email: rpedrottivf@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  RicardoPedrotti
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ricardo_pedrotti
linkedin_username: ricardo-pedrotti-38a46411b
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  **Hey, nice having you here!** :) This page is intended to go over *most relevant details* about my professional life. If you want a shot version of it, please click [here](https://www.linkedin.com/in/ricardo-pedrotti-38a46411b/) or the Linkedin logo above.


  <mark>My name is Ricardo Pedrotti and I'm a Brazilian/Italian Data Engineer.</mark>
  
  **I currently live in London and work for Global Savings Group as the Lead Data Engineer for 2 distinct multicultural teams.** As GSG, Our mission is to empower consumers by delivering rewards on every purchase they make.

  My role as a Lead Data Engineer is to leverage the company with the best processes and information for any kind of analytics application while also enabling the team members' growth and help them to reach their full potential in GSG and in their careers.
  
  My whole carreer has been based on the "new" *on cloud data market*. I have a strong experience with two of the main cloud providers: <mark>AWS</mark> and <mark>Azure</mark>.
  
  <mark>My Main Tech Skills are</mark>: Python, Spark, Scala, Overall SQL, AWS and Azure Data Services (S3, EMR, Athena,, Kinesis Firehose, Blob Storage, DataBricks...), AWS and Azure CICD Tools (Code Deploy, Code Build, Azure Pipelines...), Airflow, Self Service BI, Docker among many others.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More...
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and software engineering, some of my other interests and hobbies are:
   - Mountain Biking
   - Rockets and Space Exploration
   - DIY Tech
   - Formula One
   - Lego
   - Gaming, Music, Travelling...

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
