# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ricardo Pedrotti
title: Data Engineer
email: rpedrottivf@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  RicardoPedrotti
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ricardopedrotti
linkedin_username: ricardo-pedrotti-38a46411b
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hey, nice having you here! :)
  My name is Ricardo Pedrotti and I'm a Data Engineer. I like to be a hands-on person and understand the details of things I admire. My whole carreer has been based on the new on cloud data market.
I consider my friendships to be my most valuable asset (Together with boardgames and my bicycle, of course).

  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and software engineering, some of my other interests and hobbies are:
   - Mountain Biking
   - Rockets and Space Exploration
   - DIY Tech
   - Formula One
   - Lego
   - Gaming, Music, Travelling...
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
